Support events listening
leonardocustodio/polkadart pull request #344
Opened 2023-10-30 03:55 UTC by justkawal

### Supports events runtime subscription:

Steps:

- When listening to events fetched latest runtime metadata very first time only
- Decodes the metadata and creates a scale_codec
- After the scale codec is created reuses the same instance to decode the events on the fly.

2023-10-30 23:27 UTC, leonardocustodio requested changes

2023-10-30 23:27 UTC, leonardocustodio commented on packages/polkadart/example/polkadart_example.dart
> +  final state = StateApi(polkadart);
Can you leave the other examples? They are useful for the rest of the PR that I'm making

2023-10-31 02:03 UTC, justkawal commented on packages/polkadart/example/polkadart_example.dart
> +  final state = StateApi(polkadart);
Done Changed back.

2023-10-31 10:20 UTC, leonardocustodio approved these changes

2023-10-31 10:20 UTC, merged