Create schnorrkel package
leonardocustodio/polkadart pull request #355
Opened 2023-11-04 05:28 UTC by justkawal

2023-11-04 17:05 UTC, leonardocustodio reviewed
Though the name is correct it is too difficulty to type and so to find in pub.dev let's name it sr25519

2023-11-04 17:16 UTC, justkawal commented
okay

2023-12-01 00:49 UTC, clangenb commented
May I ask for a state update on this PR?

2023-12-01 02:00 UTC, justkawal commented
> May I ask for a state update on this PR?

Its nearly completed, just adding more test-cases for more coverage....

2023-12-02 19:56 UTC, justkawal commented
Sample usage:

```dart
import 'dart:convert';
import 'package:merlin/merlin.dart' as merlin;
import 'package:sr25519/sr25519.dart';

void main() {
  final msg = utf8.encode('hello friends');
  final signingCtx = utf8.encode('example');

  final merlin.Transcript signingTranscript = Sr25519.newSigningContext(signingCtx, msg);

  final merlin.Transcript verifyTranscript = Sr25519.newSigningContext(signingCtx, msg);

  final keypair = Sr25519.generateKeyPair();

  final (priv, pub) = (keypair.secretKey, keypair.publicKey);

  final Signature sig = priv.sign(signingTranscript);

  final (verified, _) = pub.verify(sig, verifyTranscript);

  assert(verified == true);
}
```

2023-12-02 21:47 UTC, leonardocustodio commented
Isn't it integrated with the KeyPairclass yet? We shouldn't have to call sr25519 directly. Instead we just call keypair and specify the algorithm being sr25519 the default

2023-12-09 08:21 UTC, justkawal commented
> Isn't it integrated with the Keypair/Keyring class yet? We shouldn't have to call sr25519 directly. Instead we just call keyring and specify the algorithm being sr25519 the default

Yes, done the Keyring integration and with KeyPair as well....
Sorry @leonardocustodio , It took a while but was making sure everything running good with quality test-cases.

2023-12-09 08:32 UTC, justkawal commented
Example:

```dart
final keyring = Keyring(); 
// keypair creation inside keyring defaults to ed25519 but can be changed from named parameters
// with KeyPairType.sr25519

keyring.add(KeyPair.sr25519.fromSeed(your seed Uint8List value));
// or KeyPair.sr25519.fromUri(.....)
// or KeyPair.sr25519.fromMnemonic(.....)

// or replace sr25519  --->  ed25519
// or Keypair.ed25519.fromUri(.....)
// or KeyPair.ed25519.fromMnemonic(.....)

final Uint8List message = utf8.encode('this is a message');
final pair = keyring.getByPublicKey(publicKey1);
final signature = pair.sign(message);

final verified = pair.verify(message, signature); // true

// ooopps anonymous pair
final anonyPair = keyring.getByPublicKey(publicKey2);
final verified = anonyPair.verify(message, signature);  // false
```

2023-12-09 08:34 UTC, justkawal commented
While deriving seed from uri, it does that by hard and soft key derivation from the recursive junctions.

2023-12-10 19:43 UTC, leonardocustodio requested changes
Overall the PR looks real good. Awesome job mate.

2023-12-10 19:43 UTC, leonardocustodio commented on packages/sr25519/pubspec.yaml
> +version: 1.0.0
Though the package seems pretty complete. Let's start with a lower version like `0.1.0` so we can promote substrate_bip39 / polkadart_keyring and this all together.

2023-12-10 19:43 UTC, leonardocustodio commented on packages/polkadart_keyring/lib/src/keyring.dart
> +        keyPairType = KeyPairType.ed25519;
As the default on-chain as `sr25519` our default should also be `sr25519`

2023-12-10 19:43 UTC, leonardocustodio commented on packages/polkadart_keyring/lib/src/keypair.dart
> +  dynamic get publicKey;
What type is this? On ed25519 we can do:
`keypair.publicKey.bytes` how we do the same on `sr25519`? We should have the same interfaces.

2023-12-10 19:43 UTC, leonardocustodio commented on packages/sr25519/CHANGELOG.md
> +## 1.0.0
Don't forget to lower here

2023-12-11 22:03 UTC, justkawal commented on packages/sr25519/CHANGELOG.md
> +## 1.0.0
Resolved

2023-12-14 03:52 UTC, justkawal commented on packages/polkadart_keyring/lib/src/keypair.dart
> +  dynamic get publicKey;
Resolved

2023-12-14 17:12 UTC, justkawal commented
Resolved conflicts and updated @leonardocustodio 
Waiting for review....

2023-12-18 19:35 UTC, justkawal commented on packages/polkadart_keyring/lib/src/sr25519.dart
> +    final seed = await SubstrateBip39.ed25519.seedFromUri(mnemonic);
Actually this is right, because in rust bindings they are doing the same.
Analysed and converted from the rust code directly, so reused the functionality.

But also I'm open to see the `test-cases` for which It will fail....

2023-12-18 19:39 UTC, justkawal commented on packages/polkadart_keyring/lib/src/ed25519.dart
> +  Future<void> unlockFromMemonic(String mnemonic, [String? password]) async {
Resolved

2023-12-18 19:39 UTC, justkawal commented on packages/polkadart_keyring/lib/src/keypair.dart
> +  Future<void> unlockFromMemonic(String mnemonic, [String? password]);
Resolved

2023-12-19 01:09 UTC, leonardocustodio commented
Can you rebase the pr? It is showing more changes than it should

2023-12-19 08:28 UTC, clangenb commented on packages/polkadart_keyring/lib/src/sr25519.dart
> +    final seed = await SubstrateBip39.ed25519.seedFromUri(mnemonic);
Alright, I don't have the technical insight here, but the naming just put me off. In this case, a comment might be nice that it is actually correct. :)

2023-12-19 18:01 UTC, leonardocustodio commented
There is only a single issue. At the `ExtrinsicPayload` class. You can see there is the `signatureType` it was hardcoded to `ed25519` as that was the only type we supported. Now, we need to set it to `00` if `ed25519` or `01` to `sr25519`. 

In this case I suggest to also make an extension where you can pass the keypair to an `Extrinsic` like it is done in polkadot-js as the following:

```
	const { signature } = registry
		.createType('ExtrinsicPayload', signingPayload, {
			version: EXTRINSIC_VERSION,
		})
		.sign(pair);
````

Would also be nice to have a helper function where I could sign the SigningPayload (not the Extrinsic class) like so:
```
	const signature = signWith(alice, signingPayload, {
		metadataRpc,
		registry,
	});
```

Besides that, everything looks really good, congratulations my friend.

2023-12-19 22:15 UTC, justkawal commented
Can you provide the permalink to the ExtrinsicPayload class?

> There is only a single issue. At the `ExtrinsicPayload` class. You can see there is the `signatureType` it was hardcoded to `ed25519` as that was the only type we supported. Now, we need to set it to `00` if `ed25519` or `01` to `sr25519`.
> 
> In this case I suggest to also make an extension where you can pass the keypair to an `Extrinsic` like it is done in polkadot-js as the following:
> 
> ```js
> 	const { signature } = registry
> 		.createType('ExtrinsicPayload', signingPayload, {
> 			version: EXTRINSIC_VERSION,
> 		})
> 		.sign(pair);
> ```
> 
> So for us, maybe something like this:
> 
> ```dart
>   final extrinsic = Extrinsic(
>     signer: publicKey,
>     method: encodedCall,
>     signature: hexSignature,
>     eraPeriod: 64,
>     blockNumber: blockNumber,
>     nonce: 0,
>     tip: 0,
>   ).encode(api.registry).sign(pair);
> ```
> 
> Would also be nice to have a helper function where I could sign the SigningPayload (not the Extrinsic class) like the following example of `tx-wrapper`:
> 
> ```js
> 	const signature = signWith(alice, signingPayload, {
> 		metadataRpc,
> 		registry,
> 	});
> ```
> 
> Besides that, everything looks really good, congratulations my friend.

2023-12-19 22:44 UTC, leonardocustodio commented
> Can you provide the permalink to the ExtrinsicPayload class?

https://github.com/leonardocustodio/polkadart/tree/main/packages/polkadart/lib/extrinsic

2023-12-22 08:00 UTC, clangenb commented on packages/polkadart_keyring/pubspec.yaml
> +    path: ../sr25519
Think that dart doesn't like this. The Pubspec.lock refers to my local filesystem, and I can't fix it with dependency overrides.

2023-12-22 08:05 UTC, clangenb commented on packages/polkadart_keyring/pubspec.yaml
> +    path: ../sr25519
This seems to be a problem with git deps only: https://github.com/dart-lang/pub/issues/3336

2023-12-22 08:10 UTC, clangenb commented on packages/polkadart_keyring/pubspec.yaml
> +    path: ../sr25519
So it seems to be a chicken-and-egg problem. May I ask you you to publish the sr25519 package to pub.dev, and then adjust the dependency here to refer to pub.dev. With this, I suppose that I can safely rely on my fork of polkadart again without any issues.

2023-12-22 11:47 UTC, leonardocustodio commented on packages/polkadart_keyring/pubspec.yaml
> +    path: ../sr25519
Yep, it needs to be published first to change it as the package doesn't exists yet. We will do as soon as the remaining comments are addressed

2023-12-27 19:02 UTC, justkawal commented
@leonardocustodio 

Updated and made a followup PR: #386

2024-01-08 15:58 UTC, leonardocustodio commented
Thanks, I'm back from holidays, I will be reviewing this in the end of the day.

2024-01-09 00:30 UTC, leonardocustodio approved these changes

2024-01-09 00:30 UTC, merged

2024-01-09 00:37 UTC, leonardocustodio commented
sr25519 published, feel free to make the changes on pubspec dependencies @justkawal 
https://pub.dev/packages/sr25519
Btw great job!!!