Ecdsa/Secp256k1 implementation
leonardocustodio/polkadart pull request #404
Opened 2024-01-29 04:49 UTC by justkawal

Add Ecdsa/Secp256k1 usage functionality:
- Sign/Verify Messages
- Integrate to Keypairs
- Add a new library from ground up for secp256k1 ( Made from group up from Noble-curves reference ).
- Adds ecdsa `Hard key derivation` in substrate-bip39.
- Test wide range of cases on Ecdsa/secp256k1.

2024-01-29 12:23 UTC, leonardocustodio commented
Can we change the version to `0.1.0` we will bump everything (sr25519/ecdsa) to `1.0.0` when keyring reaches version 1

2024-01-29 15:13 UTC, leonardocustodio requested changes

2024-01-29 15:13 UTC, leonardocustodio commented on packages/polkadart_keyring/pubspec.yaml
> +publish_to: 'none' # Remove this line if you wish to publish to pub.dev
You can remove this please.

2024-01-29 15:13 UTC, leonardocustodio commented on packages/polkadart_keyring/pubspec.yaml
> +    path: ../substrate_bip39
Doesn't it work fine when changing in the override? I know for secp256k1 will not work as the package is not published yet.

2024-01-29 15:13 UTC, leonardocustodio commented on packages/secp256k1_ecdsa/CHANGELOG.md
> +## 1.0.0
0.1.0

2024-01-29 15:13 UTC, leonardocustodio commented on packages/secp256k1_ecdsa/pubspec.yaml
> +version: 1.0.0
0.1.0

2024-01-29 15:13 UTC, leonardocustodio commented on packages/secp256k1_ecdsa/pubspec.yaml
> +# repository: https://github.com/my_org/my_repo
Can fix the repository here

2024-01-29 15:13 UTC, leonardocustodio commented on packages/secp256k1_ecdsa/pubspec.yaml
> +description: A starting point for Dart libraries or applications.
Change the description please

2024-01-29 15:13 UTC, leonardocustodio commented on packages/secp256k1_ecdsa/pubspec.yaml
> +publish_to: 'none' # Remove this line if you wish to publish to pub.dev
Remove it

2024-01-29 17:45 UTC, justkawal commented on packages/polkadart_keyring/pubspec.yaml
> +publish_to: 'none' # Remove this line if you wish to publish to pub.dev
Removed. ✅

2024-01-29 17:48 UTC, justkawal commented on packages/secp256k1_ecdsa/pubspec.yaml
> +version: 1.0.0
Done ✅

2024-01-29 17:48 UTC, justkawal commented on packages/secp256k1_ecdsa/pubspec.yaml
> +# repository: https://github.com/my_org/my_repo
Done ✅

2024-01-29 17:49 UTC, justkawal commented on packages/secp256k1_ecdsa/pubspec.yaml
> +publish_to: 'none' # Remove this line if you wish to publish to pub.dev
Removed ✅

2024-01-29 17:49 UTC, justkawal commented on packages/secp256k1_ecdsa/CHANGELOG.md
> +## 1.0.0
Changed ✅

2024-01-29 17:51 UTC, justkawal commented on packages/polkadart_keyring/pubspec.yaml
> +    path: ../substrate_bip39
Done ✅

2024-01-29 17:56 UTC, leonardocustodio commented
Nice job man, I will do some manual testing and I can finish the review by the end of the day.

2024-01-29 17:59 UTC, justkawal commented
Let's complete this in next 2 weeks or as early as possible.... Haha

2024-01-29 18:36 UTC, leonardocustodio requested changes
There is an issue, I don't think it is generating the correct `public key` here you can find the address generated by polkadot-js using ecdsa:
![image](https://github.com/leonardocustodio/polkadart/assets/5619696/759e5bdb-c73e-4ccd-8728-466a6521c641)
And that's the public key of that address:
![image](https://github.com/leonardocustodio/polkadart/assets/5619696/59b6b501-5227-4ffc-8852-eb2eb309c82e)
And here we can see the public key generated by the package:
![image](https://github.com/leonardocustodio/polkadart/assets/5619696/b40d5461-ce76-4296-afea-c4d081422b20)

Also important to note that the key generated is 1 byte longer than it should be.
Correct value: `0x0d90aef20b4a64c8831c1420db3a2894d4e0d838d93acaacc3fec2f27b36db4b`
Wrong value: `0x0362cb81f6d8afe001df5b310e10b09f673c3399a63103ec6402ebbcba836619b7`

2024-01-29 18:58 UTC, leonardocustodio commented
/describe

2024-01-29 19:02 UTC, leonardocustodio commented
/generate_labels

2024-01-29 21:56 UTC, leonardocustodio requested changes
Since we now have `ecdsa` support and thus the ss58 public key and the keyring public key doesn't always match, I think we should add another method to get the `raw address`.

Check the following example from polkadot-js:
```js
const keyring = new Keyring({ ss58Format: 42, type: 'ecdsa' });
const test = keyring.addFromMnemonic('resource mirror lecture smooth midnight muffin position cup pepper fruit vanish also', {});
console.log("Public key:", u8aToHex(test.publicKey));
console.log('SS58 public key', u8aToHex(test.addressRaw));

Public key: 0x0362cb81f6d8afe001df5b310e10b09f673c3399a63103ec6402ebbcba836619b7
SS58 public key 0x0d90aef20b4a64c8831c1420db3a2894d4e0d838d93acaacc3fec2f27b36db4b
```

When using `subkey` we can check the values
```sh
subkey inspect --scheme ecdsa "resource mirror lecture smooth midnight muffin position cup pepper fruit vanish also"
Secret phrase:       resource mirror lecture smooth midnight muffin position cup pepper fruit vanish also
  Network ID:        substrate
  Secret seed:       0x6e80514b03dcec9c289619fb49a2fdee158fc36b68d47ee3bf7a7c766960f142
  Public key (hex):  0x0362cb81f6d8afe001df5b310e10b09f673c3399a63103ec6402ebbcba836619b7
  Account ID:        0x0d90aef20b4a64c8831c1420db3a2894d4e0d838d93acaacc3fec2f27b36db4b
  Public key (SS58): KWAwr9VzcMSyi6AkY4CyC2bb9MziieDYeTtjnmmwXZAckBxeJ
  SS58 Address:      5CNVTcMkkxbBCBKviDvZG1JovUxj1EL2bSbu1NHBjf4djhEE
```

This is important because with other methods you could just pass their public key to a `MultiAddress` for example:
```dart
 final dest = $MultiAddress().id(hex.decode(publicKey));
```

But with ecdsa that would not be possible as the ecdsa public key is not used for that. In other crypto methods, sr25519 and ed25519 they always match that's why there is no problem with the other methods. You can see an example using sr25519 below:

```sh
subkey inspect "resource mirror lecture smooth midnight muffin position cup pepper fruit vanish also" 
Secret phrase:       resource mirror lecture smooth midnight muffin position cup pepper fruit vanish also
  Network ID:        substrate
  Secret seed:       0x6e80514b03dcec9c289619fb49a2fdee158fc36b68d47ee3bf7a7c766960f142
  Public key (hex):  0xbec6019e0194ba7c20dd706ca800dc61c749763bb4fb9464f4d655bce169d104
  Account ID:        0xbec6019e0194ba7c20dd706ca800dc61c749763bb4fb9464f4d655bce169d104
  Public key (SS58): 5GNqmvkkyXMZamAfTgRefneyAi7tZthypdkqCmRfuY3hc41D
  SS58 Address:      5GNqmvkkyXMZamAfTgRefneyAi7tZthypdkqCmRfuY3hc41D

```

2024-01-30 05:20 UTC, justkawal commented
> ```js
> const keyring = new Keyring({ ss58Format: 42, type: 'ecdsa' });
> const test = keyring.addFromMnemonic('resource mirror lecture smooth midnight muffin position cup pepper fruit vanish also', {});
> console.log("Public key:", u8aToHex(test.publicKey));
> console.log('Account ID:', u8aToHex(test.addressRaw));
> ```

Done, Changed requested code.

2024-01-30 13:04 UTC, merged

2024-01-30 13:17 UTC, leonardocustodio commented
Released under `secp256k1_ecdsa 0.1.0` and `polkadart_keyring 0.3.2`