MultiSig Implementation
leonardocustodio/polkadart pull request #417
Opened 2024-01-30 22:09 UTC by justkawal

MultiSig
  - Implements MultiSig Address Creation
  - Test Cases
  - Closes #360

2024-01-31 00:21 UTC, leonardocustodio requested changes
Also, it is important to note that the scope of this ticket isn't only multisig account creation. We also need to be able to send the call, decode the call, make the deposit, cancel the call.

You can find more information in the following links:
https://wiki.polkadot.network/docs/learn-guides-accounts-multisig
https://support.polkadot.network/support/solutions/articles/65000181826-how-to-create-and-use-a-multisig-account

2024-01-31 00:21 UTC, leonardocustodio commented on packages/polkadart_keyring/README.md
> +        ], 2);
Would be nice to put here in the docs that 2 is the threshold and what it means, here you can find a reference text: https://wiki.polkadot.network/docs/learn-account-multisig

2024-01-31 20:52 UTC, justkawal commented
Looking into it.

2024-02-05 01:16 UTC, justkawal commented
> Also, it is important to note that the scope of this ticket isn't only multisig account creation. We also need to be able to send the call, decode the call, make the deposit, cancel the call.
> 
> You can find more information in the following links: https://wiki.polkadot.network/docs/learn-guides-accounts-multisig https://support.polkadot.network/support/solutions/articles/65000181826-how-to-create-and-use-a-multisig-account

I researched the internet, but wasn't able to find a code sample or example to mimic/implement the multisig (`initiate`, `approveAsMulti`, `asMulti`, and `cancel`).

Whenever you find time, let me know. @leonardocustodio

2024-02-05 18:01 UTC, leonardocustodio commented
You can find the methods here: https://github.com/paritytech/txwrapper-core/tree/main/packages/txwrapper-substrate/src/methods/multisig

2024-02-19 00:21 UTC, justkawal commented
@leonardocustodio I guess the PR looks good now....

2024-02-19 02:04 UTC, leonardocustodio commented
Is this also for #359 or only multisig?

2024-02-19 03:34 UTC, justkawal commented
> Is this also for #359 or only multisig?

Umm.... Yes,
I have added functionality to get and parse every `signedExtensions` from the `chain metadata` even the `custom` as well and provide access to that from `TypeRegistry`....

2024-02-20 02:51 UTC, leonardocustodio approved these changes
lgtm

2024-02-20 02:51 UTC, merged