Work In Progress branch - Contracts - ABI
leonardocustodio/polkadart pull request #489
Opened 2024-10-20 19:01 UTC by justkawal

Work in Progress for Contracts ABI Code.

2024-10-20 19:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/leonardocustodio/polkadart?pullRequest=489) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/leonardocustodio/polkadart?pullRequest=489) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/leonardocustodio/polkadart?pullRequest=489) it.</sub>

2024-11-24 15:16 UTC, justkawal commented
@leonardocustodio PR is ready for review.

2024-11-24 16:56 UTC, leonardocustodio requested changes
Can you add it to the workflows so the tests runs?

2024-12-01 00:30 UTC, justkawal commented
* [x] Renamed from Abi to Ink Abi.
* [x] Added Ink Abi to desired Workflows.

2024-12-01 20:21 UTC, leonardocustodio approved these changes

2024-12-01 20:21 UTC, merged